# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        db:
          entity:
              class: CodeExperts\EcommerceBundle\Entity\User
              property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: db
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    encoders:
            CodeExperts\EcommerceBundle\Entity\User:
                algorithm: bcrypt

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN}